# Generated by Django 5.1 on 2024-09-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_alter_ganho_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='cliente_cpf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
